### ISSUE TITLE
Go module

### ISSUE THREAD

**Issue by 9glenda** [sherlock-project/enola#8]
Will this be distributed as a go module to be able to scan for OSINT from another golang application using this module?

**Comment by TheYahya** [comment]
I'm not sure what you mean, Can you elaborate a bit please?!

**Comment by 9glenda** [comment]
In pyton terms it would be a libary.
Basically a package you can import in any go project which allows you to use the scanning feature of enola but doesn't add the tui

**Comment by TheYahya** [comment]
Yes, It's possible.

**Comment by 9glenda** [comment]
could you provide an example of doing so in the readme?
